INSERT INTO TB_CATEGORY (name, created_at) VALUES ('COMPUTER', NOW());
INSERT INTO TB_CATEGORY (name, created_at) VALUES ('ELETRONICS', NOW());
INSERT INTO TB_CATEGORY (name, created_at) VALUES ('BOOKS', NOW());